application: wikitheoria
version: 144
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /static
  static_dir: static

- url: /static/images
  static_dir: static/images
  
- url: /static/css
  static_dir: static/css
    
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /module/new.*
  script: modules.py
  login: required

- url: /module/edit.*
  script: modules.py
  login: required

- url: /modules.*
  script: modules.py

- url: /administration.*
  script: admin.py
  login: required

- url: /article/new.*
  script: articles.py
  login: required

- url: /article/edit.*
  script: articles.py
  login: required
  
- url: /articles.*
  script: articles.py
 
- url: /users.*
  script: users.py
  
- url: /contribute/definition.*
  script: terms.py
  login: required
  
- url: /contribute/term.*
  script: terms.py
  login: required
  
- url: /terms.*
  script: terms.py
  
- url: /api.*
  script: api.py
  
- url: /.*
  script: main.py
  
